In [ ]:
import numpy as np


In [ ]:
a = np.array([1, 2, 3])
r= np.asarray(a, dtype="str")
print(r)

['1' '2' '3']


In [ ]:
s=b"helloooooooooooooooooooo"
z= np.frombuffer(s, dtype="int")
print(z)

[8029759184975979880 8029759185026510703 8029759185026510703]


In [ ]:
s = [1,2,3,4,5]
z = np.fromiter(s, dtype=int)
print(z)

[1 2 3 4 5]


In [ ]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [ ]:
a = np.linspace(0,10,3,endpoint=False,retstep=True,dtype=int)
print(a)

(array([0, 3, 6]), 3.3333333333333335)


In [ ]:
a = np.logspace(10,10000,num=4,base=10)
print(a)

[1.e+10    inf    inf    inf]


/usr/local/lib/python3.10/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


In [ ]:
import numpy as np
x= np.zeros((2,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]]


In [ ]:
x=np.full((2,3),5,dtype=float)
print(x)

[[5. 5. 5.]
 [5. 5. 5.]]


In [ ]:
x=np.eye(3,dtype=int)
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
x=np.array([[1,2,3],[4,5,6]])
print(np.shape(x))

(2, 3)


In [ ]:
x=np.array([[1,2,3],[4,5,6]])
print(np.reshape(x,(3,2)))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x[0,2])

3


In [ ]:
x=np.array([[1,2,3],[4,5,6]])
print(x[0:2,1])

[2 5]


In [ ]:
x=np.array([1,2,3,4,5,6])
print(x[::2])

[1 3 5]


In [ ]:
import numpy as np
x =np.array([1,2,3,4,5],dtype="S")
print(x)


[b'1' b'2' b'3' b'4' b'5']


In [ ]:
import numpy as np
x =np.array([1,2,3,4,5])
y=x.astype("U")
print(y)

['1' '2' '3' '4' '5']


In [ ]:
import numpy as np
x =np.array([1,2,3,4,5])
y=x.copy()
y[0]=4
print(x)
print(y)

[1 2 3 4 5]
[4 2 3 4 5]


In [ ]:
import numpy as np
x =np.array([1,2,3,4,5])
y=x.view()
y[0]=4
print(x)
print(y)

[4 2 3 4 5]
[4 2 3 4 5]


In [ ]:
import numpy as np
x=np.arange(0,4).reshape(2,2)
y=np.arange(0,4).reshape(2,2)
z=np.concatenate((x,y),axis=1)
print(z)



[[0 1 0 1]
 [2 3 2 3]]


In [ ]:
import numpy as np
x=np.arange(0,4).reshape(2,2)
y=np.arange(0,4).reshape(2,2)
z=np.stack((x,y),axis=1)
print(z)

[[[0 1]
  [0 1]]

 [[2 3]
  [2 3]]]


In [ ]:
import numpy as np
x=np.arange(0,4).reshape(2,2)
y=np.arange(0,4).reshape(2,2)
z=np.hstack((x,y))
print(z)

[[0 1 0 1]
 [2 3 2 3]]


In [ ]:
import numpy as np
x=np.arange(0,4).reshape(2,2)
y=np.arange(0,4).reshape(2,2)
z=np.vstack((x,y))
print(z)

[[0 1]
 [2 3]
 [0 1]
 [2 3]]


In [ ]:
import numpy as np
a=np.arange(10)
print(a,"\n")
b=np.array_split(a,3)
print(b,"\n")
c=np.split(a,5)
print(c,"\n")
d=np.hsplit(a,5)
print(d,"\n")
z=np.arange(8).reshape(2,4)
e=np.vsplit(z,2)
print(e)

[0 1 2 3 4 5 6 7 8 9] 

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])] 

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])] 

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])] 

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]


In [ ]:
import numpy as np
a=np.arange(10)
print(a)
x=np.where(a==5)
print(x)


[0 1 2 3 4 5 6 7 8 9]
(array([5]),)


In [ ]:
a=np.arange(10)
print(a)
x=np.searchsorted(a,5)
print(x)

[0 1 2 3 4 5 6 7 8 9]
5


In [ ]:
import numpy as np
a=np.arange(4)
print(a)
x=np.searchsorted(a,15)
print(x)

[0 1 2 3]
4


In [ ]:
import numpy as np
a=np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(a)
x=np.array([('abc','20','56'),('efg','25','59')])
print(x)
z=np.sort(x)
print(z)


[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[['abc' '20' '56']
 ['efg' '25' '59']]
[['20' '56' 'abc']
 ['25' '59' 'efg']]


In [ ]:
import numpy as np
a=np.arange(1,7).reshape(2,3)
b=np.arange(7,13).reshape(2,3)
print(a,"\n")
print(b,"\n")
z=np.add(a,b)
print(z,"\n")
z=np.subtract(b,a)
print(z,"\n")
z=np.multiply(b,a)
print(z,"\n")
z=np.divide(b,a)
print(z)


[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]] 

[[ 8 10 12]
 [14 16 18]] 

[[6 6 6]
 [6 6 6]] 

[[ 7 16 27]
 [40 55 72]] 

[[7.  4.  3. ]
 [2.5 2.2 2. ]]


In [ ]:
import numpy as np
a=np.arange(9).reshape(3,3)
print(np.amax(a))
print(np.amin(a))
print(np.average(a))
print(np.median(a))


8
0
4.0
4.0


In [ ]:
x=0
for i in range(9):
    x=x+i
print(x)
z=x/9
print(z)

36
4.0
